"""add copilot capabilities column

Revision ID: 18d0209e82c5
Revises: 652f5974d46b
Create Date: 2026-09-17 09:16:06.613047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18d0209e82c5'
down_revision: Union[str, None] = '652f5974d46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copilots', sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"human_in_the_loop": false}\'::jsonb'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copilots', 'capabilities')
    # ### end Alembic commands ###
