"""add document index_status field

Revision ID: 4dcb7463f6b6
Revises: bd0c53a8763d
Create Date: 2026-08-05 04:29:02.206978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dcb7463f6b6'
down_revision: Union[str, None] = 'bd0c53a8763d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('index_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'index_status')
    # ### end Alembic commands ###
