"""add auth, rbac, and multi-tenancy tables

Revision ID: 535cfeba2bb4
Revises: 25f4b6bf6828
Create Date: 2026-08-05 15:43:01.997152

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535cfeba2bb4'
down_revision: Union[str, None] = '25f4b6bf6828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # Seed the five enterprise roles. Referenced by name (see
    # app/models/role.py's SUPER_ADMIN/ORGANIZATION_ADMIN/... constants),
    # not by a hardcoded id, so this data migration is the only place
    # that needs to know these UUIDs.
    roles_table = sa.table(
        'roles',
        sa.column('id', sa.UUID()),
        sa.column('name', sa.String()),
        sa.column('description', sa.String()),
    )
    op.bulk_insert(
        roles_table,
        [
            {
                'id': uuid.uuid4(),
                'name': 'super_admin',
                'description': 'Full platform access across all organizations.',
            },
            {
                'id': uuid.uuid4(),
                'name': 'organization_admin',
                'description': 'Full access within their own organization.',
            },
            {
                'id': uuid.uuid4(),
                'name': 'copilot_creator',
                'description': 'Can create and manage copilots within their organization.',
            },
            {
                'id': uuid.uuid4(),
                'name': 'knowledge_manager',
                'description': 'Can manage knowledge sources and documents within their organization.',
            },
            {
                'id': uuid.uuid4(),
                'name': 'end_user',
                'description': 'Can use copilots (chat) within their organization.',
            },
        ],
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.add_column('copilots', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'copilots', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('knowledge_sources', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'knowledge_sources', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_sources', type_='foreignkey')
    op.drop_column('knowledge_sources', 'organization_id')
    op.drop_constraint(None, 'copilots', type_='foreignkey')
    op.drop_column('copilots', 'organization_id')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('organizations')
    # ### end Alembic commands ###
