"""add graph rag tables

Revision ID: 652f5974d46b
Revises: 535cfeba2bb4
Create Date: 2026-09-12 14:19:11.658859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652f5974d46b'
down_revision: Union[str, None] = '535cfeba2bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'canonical_name', 'entity_type', name='uq_graph_entities_document_canonical_name_type')
    )
    op.create_index('ix_graph_entities_document_id', 'graph_entities', ['document_id'], unique=False)
    op.create_table('graph_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['graph_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['graph_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'source_entity_id', 'target_entity_id', 'relationship_type', name='uq_graph_relationships_document_source_target_type'),
    sa.UniqueConstraint('id', 'document_id', name='uq_graph_relationships_id_document_id')
    )
    op.create_index('ix_graph_relationships_document_id', 'graph_relationships', ['document_id'], unique=False)
    op.create_index('ix_graph_relationships_source_entity_id', 'graph_relationships', ['source_entity_id'], unique=False)
    op.create_index('ix_graph_relationships_target_entity_id', 'graph_relationships', ['target_entity_id'], unique=False)
    op.create_table('graph_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('relationship_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.String(length=255), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id', 'document_id'], ['graph_relationships.id', 'graph_relationships.document_id'], name='fk_graph_evidence_relationship_document', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relationship_id', 'chunk_id', name='uq_graph_evidence_relationship_chunk')
    )
    op.create_index('ix_graph_evidence_chunk_id', 'graph_evidence', ['chunk_id'], unique=False)
    op.create_index('ix_graph_evidence_document_id', 'graph_evidence', ['document_id'], unique=False)
    op.create_index('ix_graph_evidence_relationship_id', 'graph_evidence', ['relationship_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_graph_evidence_relationship_id', table_name='graph_evidence')
    op.drop_index('ix_graph_evidence_document_id', table_name='graph_evidence')
    op.drop_index('ix_graph_evidence_chunk_id', table_name='graph_evidence')
    op.drop_table('graph_evidence')
    op.drop_index('ix_graph_relationships_target_entity_id', table_name='graph_relationships')
    op.drop_index('ix_graph_relationships_source_entity_id', table_name='graph_relationships')
    op.drop_index('ix_graph_relationships_document_id', table_name='graph_relationships')
    op.drop_table('graph_relationships')
    op.drop_index('ix_graph_entities_document_id', table_name='graph_entities')
    op.drop_table('graph_entities')
    # ### end Alembic commands ###
