"""add document ingestion fields

Revision ID: bd0c53a8763d
Revises: 632500a70b87
Create Date: 2026-08-04 17:36:32.987468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0c53a8763d'
down_revision: Union[str, None] = '632500a70b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('storage_path', sa.String(length=1000), nullable=True))
    op.add_column('documents', sa.Column('extracted_text_path', sa.String(length=1000), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=150), nullable=True))
    op.add_column('documents', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('processing_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'file_size_bytes')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'extracted_text_path')
    op.drop_column('documents', 'storage_path')
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
